env_type: robotwin
total_num_envs: null
auto_reset: False
ignore_terminations: False
use_rel_reward: True
seed: 0
group_size: 1
use_fixed_reset_state_ids: True
max_steps_per_rollout_epoch: 10
max_episode_steps: 10 # max episode steps for truncation

image_size: [224, 224]

video_cfg:
  save_video: False
  info_on_video: True
  video_base_dir: ${runner.logger.log_path}/video/train
